### ISSUE TITLE
Error connecting to ProjectObsidian server using CPE

### ISSUE THREAD

**Issue by Hedwig7s** [ViaVersion/ViaLegacy#76]
Error (ViaProxy):
```
[17:56:41] [Netty Epoll Client IO #2/WARN] (ViaVersion) ERROR IN Protocolc0_28_30Toa1_0_15 IN REMAP OF PLAY 0x0F->0x0F
[17:56:41] [Netty Epoll Client IO #2/ERROR] (ViaProxy) Caught unhandled netty exception
 io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: net.raphimc.vialegacy.protocol.classic.c0_28_30toa1_0_15.Protocolc0_28_30Toa1_0_15$$Lambda$3681/0x00007fcf505e4b28
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:500) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.3.1.jar:?]
	at net.raphimc.vialoader.netty.ViaCodec.channelRead(ViaCodec.java:81) ~[ViaProxy-3.3.1.jar:?]
	at net.raphimc.viaproxy.protocoltranslator.impl.ViaProxyViaCodec.channelRead(ViaProxyViaCodec.java:41) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) [ViaProxy-3.3.1.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) [ViaProxy-3.3.1.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) [ViaProxy-3.3.1.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [ViaProxy-3.3.1.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: net.raphimc.vialegacy.protocol.classic.c0_28_30toa1_0_15.Protocolc0_28_30Toa1_0_15$$Lambda$3681/0x00007fcf505e4b28
Caused by: java.lang.NullPointerException: Cannot invoke "net.raphimc.vialegacy.protocol.classic.c0_28_30toa1_0_15.storage.ClassicServerTitleStorage.isFlyEffectivelyEnabled()" because "serverTitleStorage" is null
	at net.raphimc.vialegacy.protocol.classic.c0_28_30toa1_0_15.storage.ClassicOpLevelStorage.setOpLevel(ClassicOpLevelStorage.java:91) ~[ViaProxy-3.3.1.jar:?]
	at net.raphimc.vialegacy.protocol.classic.c0_28_30toa1_0_15.Protocolc0_28_30Toa1_0_15.lambda$registerPackets$3(Protocolc0_28_30Toa1_0_15.java:339) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[ViaProxy-3.3.1.jar:?]
	at net.raphimc.vialegacy.api.protocol.StatelessProtocol.transform(StatelessProtocol.java:33) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[ViaProxy-3.3.1.jar:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:246) ~[ViaProxy-3.3.1.jar:?]
	at net.raphimc.vialoader.netty.ViaCodec.decode(ViaCodec.java:57) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[ViaProxy-3.3.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) ~[ViaProxy-3.3.1.jar:?]
	... 46 more
```
ProjectObsidian log:
```
[LOG][NETWORK]: New Connection From ('127.0.0.1', 55416)
[WARN][NETWORK]: User Hedwig7s tried logging in with invalid verification key 0! (irrelevant name verification is off)
[LOG][NETWORK]: Client Supports CPE, Starting CPE Negotiation
[WARN][NETWORK]: Ip ('127.0.0.1', 55416) Incomplete Read Error. Closing Connection.
[CHAT][GLOBAL]: &2Hedwig7s disconnected from the server!
```

This happens in both ViaProxy and ViaFabricPlus
ProjectObsidian: https://github.com/EdwardJXLi/ProjectObsidian

**Comment by Hedwig7s** [comment]
Note: This only occurs with c0.30 CPE not c0.28-c0.30

**Comment by RaphiMC** [comment]
Fixed. To apply the fix to ViaProxy or ViaFabricPlus download the latest ViaLegacy jar file from https://ci.viaversion.com/view/Libs/job/ViaLegacy/ and put it in the jars folder. (ViaFabricPlus has that folder in .minecraft/config/viafabricplus/jars and ViaProxy has it in the same folder as the ViaProxy jar file)

Don't forget to remove that file again after updating either VFP or VP
